---
title: Writers Workshop
---

## Writers Workshop

Writers Workshop is a weekly co-working meeting where we work on our individual projects *together*. It is especially difficult to stay focused while writing, and these workshops provide a level of accountability that helps us move our writing forward.

Meetings are virtual and typically 2-3 hours in length. You should have your materials ready before the workshop begins, so you can focus on your writing.

1.  Have all your materials ready before the workshop begins. Identify a small manageable chunk of writing to complete during the workshop. For example, *I will work on paragraph 3 of my introduction. If I have extra time, I will begin on my methods.*

    Turn off ALL distractions (no email or web browser, turn off phone, etc)

2.  First 5 minutes of workshop-- everyone briefly introduces the work they hope to complete in the first 90 min of the workshop.

    Select a person to keep the time-- they will give a 5 minute warning before the end of the 90 minutes.

3.  Work on your section with videos on, and your sound muted. Stay focused on your one specific goal and avoid all distractions. Do not do anything that would distract the others from their work.

4.  At 90 min mark, everyone briefly discuss how things went (if they had any obstacles). Take a 15 minute break

5.  Everyone briefly discuss what they will do for the final 60 min of the workshop (one manageable chunk of writing). Identify a person to keep the time. Work quietly (with videos on, sound muted) until the 5 minute warning is given.

6.  Everyone give a brief update on what they accomplished, how they feel about their work.

***For additional information:***

Writing Science: What makes scientific writing hard and how to make it easier (Kathleen Grogan). [**https://doi.org/10.1002/bes2.1800**](https://doi.org/10.1002/bes2.1800)

Defining the Role of Authors and Contributors (ICMJE). Link [here](https://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html).

A guide to getting published in Ecology and Evolution (BES). Link [here](https://www.britishecologicalsociety.org/wp-content/uploads/BES-Guide-to-Getting-Published.pdf).
