---
title: Permits & Reporting
---

## NOAA Protected Resources Permit

### Permits Numbers

PR1 Permit #0774-1437 from 4/16/1998 - 6/30/2004\
PR1 Permit #774-1714 from 06/30/2004 - 7/7/2010\
Permit \# 14097 from 07/07/2010-06/30/2016\*\
Permit #19091 from 05/17/2016 -- 04/21/2021\
Permit #22306 04/21/2021 -- 04/30/2026

### Permit Reporting

An automated script can be found [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/63ad139ac5c49cc3a80f1ef8a3f3c8bcbc2416ac/Scripts/PR_Takes.R) for pulling the necessary protected resources reporting data from our [sightings data](https://spotter.conserve.io/spotter/projects). This script does not produce the final Take Report needed for this permit. It does return takes per species, which can be added to the final Take Report provided by the permit coordinator. Download the script and follow the directions for each reporting cycle. Contact Kourtney Burger (kourtney.burger\@noaa.gov) with any questions/concerns.

## NOAA Sanctuaries Permit

### Permit Numbers

MULTI-2019-005 from 06/04/2019 - 04/20/2024

### Permit Reporting

An automated script can be found [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/63ad139ac5c49cc3a80f1ef8a3f3c8bcbc2416ac/Scripts/NMS_Reporting.R) for pulling the necessary Sanctuary reporting data from our [Deployment Details spreadsheet](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit#gid=395545420). Download the script and follow the directions for each reporting cycle. Contact Kourtney Burger (kourtney.burger\@noaa.gov) with any questions/concerns.

## Fish & Wildlife Permits

Add Content Here

## Navy Agreement

### Reporting

An automated script can be found [here](https://github.com/SAEL-SWFSC/SAEL-lab-manual/blob/5c9712776262ca1b460776cf1bebcb6e7507e163/Scripts/NMFS-Navy_PAM-Deployments.R) for pulling the necessary Navy reporting data from our [Deployment Details spreadsheet](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit#gid=395545420). Download the script and follow the directions for each reporting cycle. Contact Kourtney Burger (kourtney.burger\@noaa.gov) with any questions/concerns.
