---
title: General Lab Safety
---

## Safety Resources

There are many resources on the [Intranet](https://sites.google.com/noaa.gov/inside-swfsc/home/administrative/safety?pli=1&authuser=1). Some examples include the latest information on COVID-19, the NOAA Emergency Notification System, and the NOAA Safety Incident/Accident reporting home page. If you are working onsite (La Jolla) you should familiarize yourself with these links along with how to report an incident if one occurs.

## Chemical Inventory

-   Currently SAEL only possesses commercially available (over the counter) products and these are not required to be a part of the chemical inventory.

    -   As such, we do not currently have a chemical inventory (updated Feb 2023).

## Organization

-   Keep lab tidy and clean. If you start on a project and intend to keep working on it over a few days (i.e. building equipment) please clean up after you have completed work.

-   If you notice that something is running low (i.e. electrical tape, crab floats, nuts and bolts) please contact Shannon Rankin or Kourtney Burger so that they may order more supplies.
